apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodeapp
spec:
    replicas: 2
    selector:
        matchLabels:
          app: nodeapp
    template:
        metadata:
          name: nodeapp
          labels:
            app: nodeapp
        spec:
          containers:
            - name: nodeapp
              image: 096501930205.dkr.ecr.us-east-1.amazonaws.com/kpb-capstone:latest
          tolerations:
            - key: special
              value: 'true'
              operator: Equal
              effect: NoSchedule
          affinity:
            nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                        - key: project
                          operator: In
                          values:
                          - kpb-capstone